#!/bin/python3

import sys


n = int(input().strip())

count = 0
flag = []
st_n = True
for i in range(len(str_num)):
  if str_num[i] == "1":
    count += 1
  elif str_num[i] == "0":
    while st_n:
      flag.append(count)
      break
    count = 0
  else:
    st_n = False
  flag.append(count)

print (max(flag))
